{
  "FaultLabel": "Resolved power cut",
  "Type": "ResolvedFault",
  "Icon": "icon-success",
  "ShowViewOnMapCTA": false,
  "UnderReview": false,
  "AdditionalFaultInfo": "Good news! The electricity in your area has been restored. The power cut was caused by an unexpected incident on our underground cable that provides your supply.",
  "CTAs": [],
  "faultNumber": "40799313",
  "multipleFaultNumbers": null,
  "date": "2021-02-14T14:55:17",
  "region": "Poulton-Le-Fylde",
  "faultType": "Resolved Fault",
  "faultStatus": "Resolved",
  "previousFaultStatus": "Resolved",
  "consumersOff": 0,
  "estimatedTimeOfRestoration": null,
  "estimatedTimeOfRestorationMajority": "2021-02-14T14:55:17",
  "information": "",
  "actualTimeOfRestoration": "2021-02-14T14:55:17",
  "outageCentrePoint": {
    "lat": 53.84805,
    "lng": -2.999805
  },
  "outageLocations": null,
  "AffectedPostcodes": " FY6 7LT, FY6 7RY, FY6 7SG, FY6 7SQ",
  "EtrMUnderReview": true,
  "WebTMSFaultType": "U/GS"
}