{
  "FaultLabel": "Resolved power cut",
  "Type": "ResolvedFault",
  "Icon": "icon-success",
  "ShowViewOnMapCTA": false,
  "UnderReview": false,
  "AdditionalFaultInfo": "Good news! The electricity in your area has been restored. The power cut was caused by an unexpected incident on our underground cable that provides your supply.",
  "CTAs": [],
  "faultNumber": "40790036",
  "multipleFaultNumbers": null,
  "date": "2020-12-11T09:00:16",
  "region": "Poulton-Le-Fylde",
  "faultType": "Resolved Fault",
  "faultStatus": "Resolved",
  "previousFaultStatus": "Resolved",
  "consumersOff": 0,
  "estimatedTimeOfRestoration": "2020-12-11T09:30:00",
  "estimatedTimeOfRestorationMajority": "2020-12-11T09:00:16",
  "information": "",
  "actualTimeOfRestoration": "2020-12-11T09:00:16",
  "outageCentrePoint": {
    "lat": 53.843236,
    "lng": -2.973815
  },
  "outageLocations": null,
  "AffectedPostcodes": " FY6 8JL, FY6 8JS, FY6 8JT, FY6 8JU, FY6 8JY, FY6 8TU",
  "EtrMUnderReview": false,
  "WebTMSFaultType": "U/GM"
}