{
  "FaultLabel": "Resolved power cut",
  "Type": "ResolvedFault",
  "Icon": "icon-success",
  "ShowViewOnMapCTA": false,
  "UnderReview": false,
  "AdditionalFaultInfo": "Good news! The electricity in your area has been restored. The power cut was caused by an unexpected incident on our underground cable that provides your supply.",
  "CTAs": [],
  "faultNumber": "40798218",
  "multipleFaultNumbers": null,
  "date": "2021-01-30T20:41:47",
  "region": "Poulton-Le-Fylde",
  "faultType": "Resolved Fault",
  "faultStatus": "Resolved",
  "previousFaultStatus": "Resolved",
  "consumersOff": 0,
  "estimatedTimeOfRestoration": null,
  "estimatedTimeOfRestorationMajority": "2021-01-30T20:41:47",
  "information": "",
  "actualTimeOfRestoration": "2021-01-30T20:41:47",
  "outageCentrePoint": {
    "lat": 53.856799,
    "lng": -3.008442
  },
  "outageLocations": null,
  "AffectedPostcodes": " FY6 7NN, FY6 7NW",
  "EtrMUnderReview": true,
  "WebTMSFaultType": "U/GS"
}