{
  "FaultLabel": "Resolved power cut",
  "Type": "ResolvedFault",
  "Icon": "icon-success",
  "ShowViewOnMapCTA": false,
  "UnderReview": false,
  "AdditionalFaultInfo": "Good news! The electricity in your area has been restored. The power cut was caused by an unexpected incident on our underground cable that provides your supply.",
  "CTAs": [],
  "faultNumber": "60498035",
  "multipleFaultNumbers": null,
  "date": "2020-12-05T18:15:08",
  "region": "Dalton-In-Furness",
  "faultType": "Resolved Fault",
  "faultStatus": "Resolved",
  "previousFaultStatus": "Resolved",
  "consumersOff": 0,
  "estimatedTimeOfRestoration": null,
  "estimatedTimeOfRestorationMajority": "2020-12-05T18:15:08",
  "information": "",
  "actualTimeOfRestoration": "2020-12-05T18:15:08",
  "outageCentrePoint": {
    "lat": 54.155241,
    "lng": -3.18063
  },
  "outageLocations": null,
  "AffectedPostcodes": " LA15 8DW, LA15 8LE, LA15 8PG, LA15 8PH, LA15 8PJ, LA15 8PL, LA15 8PN, LA15 8PP, LA15 8PQ, LA15 8PR, LA15 8RA, LA15 8UE",
  "EtrMUnderReview": true,
  "WebTMSFaultType": "U/GM"
}