{
  "FaultLabel": "Resolved power cut",
  "Type": "ResolvedFault",
  "Icon": "icon-success",
  "ShowViewOnMapCTA": false,
  "UnderReview": false,
  "AdditionalFaultInfo": "Good news! The electricity in your area has been restored. The power cut was caused by an unexpected incident on our underground cable that provides your supply.",
  "CTAs": [],
  "faultNumber": "60503979",
  "multipleFaultNumbers": null,
  "date": "2021-02-18T13:37:52",
  "region": "Dalton-In-Furness",
  "faultType": "Resolved Fault",
  "faultStatus": "Resolved",
  "previousFaultStatus": "Resolved",
  "consumersOff": 0,
  "estimatedTimeOfRestoration": null,
  "estimatedTimeOfRestorationMajority": "2021-02-18T13:37:52",
  "information": "",
  "actualTimeOfRestoration": "2021-02-18T13:37:52",
  "outageCentrePoint": {
    "lat": 54.146273,
    "lng": -3.183412
  },
  "outageLocations": null,
  "AffectedPostcodes": " LA13 0PE, LA15 8NG, LA15 8NJ, LA15 8NN",
  "EtrMUnderReview": true,
  "WebTMSFaultType": "U/GS"
}